# Generated by Django 5.2.16 on 2026-07-20 03:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço mensal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Em teste'), ('active', 'Ativa'), ('overdue', 'Inadimplente'), ('canceled', 'Cancelada')], default='trialing', max_length=10, verbose_name='status')),
                ('asaas_customer_id', models.CharField(blank=True, max_length=60)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=60)),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name='fim do período atual')),
                ('grace_period_days', models.PositiveSmallIntegerField(default=5, verbose_name='dias de tolerância')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
