# Generated by Django 5.2.16 on 2026-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_backfill_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='início do período atual'),
        ),
    ]
