# Generated by Django 5.2.16 on 2026-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_current_period_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='14 dias corridos a partir do cadastro (register_tenant) — acesso completo até aqui.', null=True, verbose_name='fim do período de teste'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Em teste'), ('pending', 'Aguardando pagamento'), ('active', 'Ativa'), ('overdue', 'Inadimplente'), ('canceled', 'Cancelada')], default='trialing', max_length=10, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='AsaasWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=60, verbose_name='id do payment no Asaas')),
                ('event_type', models.CharField(max_length=40, verbose_name='tipo do evento')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de webhook Asaas',
                'verbose_name_plural': 'eventos de webhook Asaas',
                'constraints': [models.UniqueConstraint(fields=('payment_id', 'event_type'), name='unique_asaas_webhook_event')],
            },
        ),
    ]
