# Generated by Django 5.2.17 on 2026-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_subscription_trial_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_employees',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Quantidade máxima de PESSOAS atendendo cliente neste plano — conta funcionário contratado E o responsável quando "também atende" está ligado (decisão do usuário em 2026-08-07: o dono ocupa vaga igual qualquer funcionário, porque também gera comissão e atende cliente; só não conta LOGIN extra, o perfil dele reaproveita o próprio User de admin — ver apps.employees.models.Employee.is_owner). Vazio = sem limite.', null=True, verbose_name='limite de funcionários'),
        ),
    ]
