# Generated by Django 5.2.17 on 2026-08-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_individual_plan_counts_owner_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Quando o admin pediu cancelamento em Meu Plano (decisão do usuário em 2026-08-08: cancelar só impede a PRÓXIMA cobrança — o acesso continua até current_period_end, o período já pago não é interrompido). Não confundir com status=canceled, que é imediato (usado pro superadmin/webhook de fato encerrado).', null=True, verbose_name='cancelada em'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_active_at',
            field=models.DateTimeField(blank=True, help_text='Primeira vez que a assinatura ficou ativa (1º pagamento confirmado) — diferente de current_period_start, que é reiniciado a cada renovação/troca de plano. Setado uma única vez, nunca sobrescrito depois.', null=True, verbose_name='data de adesão'),
        ),
    ]
