# Generated by Django 5.2.17 on 2026-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscription_canceled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='5 dias corridos a partir do cadastro (register_tenant) — acesso completo até aqui.', null=True, verbose_name='fim do período de teste'),
        ),
    ]
