# Generated by Django 5.2.17 on 2026-08-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_subscription_trial_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_whatsapp', models.CharField(blank=True, help_text='Número que recebe os pedidos de suporte abertos pelos tenants (botão "Suporte" no painel). Qualquer formato serve — normalizado igual ao WhatsApp do tenant (`Tenant.whatsapp_wa_me_number`). Vazio = botão de suporte avisa que ainda não está configurado, em vez de gerar link quebrado.', max_length=20, verbose_name='WhatsApp de suporte')),
            ],
            options={
                'verbose_name': 'configuração da plataforma',
                'verbose_name_plural': 'configurações da plataforma',
            },
        ),
    ]
