# Generated by Django 5.2.17 on 2026-08-11 20:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_is_for_sale_alter_stockmovement_reason'),
        ('services', '0001_initial'),
        ('tenants', '0015_tenant_employee_can_confirm_appointments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_recipe_links', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'insumo do serviço',
                'verbose_name_plural': 'insumos do serviço',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('service', 'product'), name='unique_service_product_recipe')],
            },
        ),
    ]
