# Generated by Django 5.2.16 on 2026-07-19 06:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        ('scheduling', '0002_appointment_unique_active_appointment_per_slot'),
        ('tenants', '0002_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], max_length=20, verbose_name='tipo (snapshot)')),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor/percentual (snapshot)')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor base do serviço')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor calculado da comissão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga')], default='pending', max_length=10, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='scheduling.appointment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ['-appointment__date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10, verbose_name='tipo')),
                ('category', models.CharField(choices=[('service_sale', 'Venda de serviço'), ('product_sale', 'Venda de produto'), ('commission_payment', 'Pagamento de comissão'), ('expense', 'Despesa'), ('other', 'Outro')], max_length=20, verbose_name='categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('other', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='scheduling.appointment')),
                ('related_stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('related_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='finance.commission')),
            ],
            options={
                'verbose_name': 'lançamento de caixa',
                'verbose_name_plural': 'lançamentos de caixa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='finance_com_tenant__c5aa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['tenant', 'category', 'created_at'], name='finance_cas_tenant__e07de1_idx'),
        ),
    ]
