# Generated by Django 5.2.16 on 2026-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('service_sale', 'Venda de serviço'), ('product_sale', 'Venda de produto'), ('commission_payment', 'Pagamento de comissão'), ('client_credit_topup', 'Recarga de crédito'), ('expense', 'Despesa'), ('other', 'Outro')], max_length=20, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('client_credit', 'Crédito do cliente'), ('other', 'Outro')], max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
