# Generated by Django 5.2.16 on 2026-08-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_commission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('service_sale', 'Venda de serviço'), ('product_sale', 'Venda de produto'), ('commission_payment', 'Pagamento de comissão'), ('client_credit_topup', 'Recarga de crédito'), ('package_sale', 'Venda de pacote'), ('expense', 'Despesa'), ('other', 'Outro')], max_length=20, verbose_name='categoria'),
        ),
    ]
