# Generated by Django 5.2.17 on 2026-08-06 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cashtransaction_category'),
        ('tenants', '0013_tenant_birthday_alert_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('is_fixed', models.BooleanField(default=True, help_text='Marcado: custo que não varia com o movimento do salão (aluguel, assinatura de software, contador). Desmarcado: varia com o volume de atendimento (taxa de cartão, material consumido por atendimento).', verbose_name='despesa fixa')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'categoria de despesa',
                'verbose_name_plural': 'categorias de despesa',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='finance.expensecategory'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_expense_category_name_per_tenant'),
        ),
    ]
