# Generated by Django 5.2.17 on 2026-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expensecategory_cashtransaction_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('service_sale', 'Venda de serviço'), ('product_sale', 'Venda de produto'), ('commission_payment', 'Pagamento de comissão'), ('client_credit_topup', 'Recarga de crédito'), ('client_debt_payment', 'Cobrança de débito anterior'), ('package_sale', 'Venda de pacote'), ('expense', 'Despesa'), ('other', 'Outro')], max_length=20, verbose_name='categoria'),
        ),
    ]
