# Generated by Django 5.2.16 on 2026-07-19 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nome fantasia')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='tenants/backgrounds/')),
                ('business_hours_note', models.CharField(blank=True, max_length=120, verbose_name='horário de funcionamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['name'],
            },
        ),
    ]
