# Generated by Django 5.2.16 on 2026-07-19 05:52

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, validators=[apps.tenants.models.validate_slug_not_reserved], verbose_name='slug'),
        ),
    ]
