# Generated by Django 5.2.16 on 2026-07-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='business_hours_note',
        ),
        migrations.CreateModel(
            name='TenantBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('is_closed', models.BooleanField(default=False, verbose_name='fechado')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='abre')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fecha')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'horário de funcionamento',
                'verbose_name_plural': 'horários de funcionamento',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'weekday'), name='unique_business_hours_weekday_per_tenant')],
            },
        ),
    ]
