# Generated by Django 5.2.16 on 2026-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_backfill_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/covers/'),
        ),
    ]
