# Generated by Django 5.2.16 on 2026-07-30 23:50

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document',
            field=models.CharField(blank=True, default='', help_text='Exigido só na hora de assinar um plano pago (Asaas precisa pra criar o cliente).', max_length=18, validators=[apps.tenants.models.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
    ]
