# Generated by Django 5.2.16 on 2026-08-04 18:38

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_theme_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner_attends',
            field=models.BooleanField(default=False, help_text='Marcado: o responsável aparece em Funcionários (marcado como "Dono"), reaproveitando o próprio login de admin — sem precisar criar um funcionário para si mesmo. `apps.employees.services.sync_owner_employee` cria/atualiza esse perfil.', verbose_name='responsável também atende clientes'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Nome do dono/responsável pelo salão — usado quando ele também atende clientes (ver `owner_attends`), sem precisar de um cadastro de funcionário à parte.', max_length=120, verbose_name='nome do responsável'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/owners/', verbose_name='foto do responsável'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='document',
            field=models.CharField(blank=True, help_text='Exigido só na hora de assinar um plano pago (Asaas precisa pra criar o cliente).', max_length=18, validators=[apps.tenants.models.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
    ]
