# Generated by Django 5.2.16 on 2026-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_owner_attends_tenant_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='birthday_alert_enabled',
            field=models.BooleanField(default=False, help_text='Marcado: no dia do aniversário de um cliente (dia/mês cadastrado na ficha dele), o painel avisa o responsável — o aviso só some quando ele clicar pra enviar a mensagem de aniversário (ver apps.clients.services.ensure_birthday_notification).', verbose_name='alerta de aniversário de cliente'),
        ),
    ]
