# Generated by Django 5.2.17 on 2026-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_birthday_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='require_birthday_on_booking',
            field=models.BooleanField(default=False, help_text='Marcado: dia e mês de nascimento passam a ser obrigatórios ao cadastrar um cliente novo — tanto no agendamento público quanto no cadastro manual pelo painel. Cliente já cadastrado sem aniversário não é bloqueado por causa disso.', verbose_name='exigir aniversário do cliente'),
        ),
    ]
