# Generated by Django 5.2.16 on 2026-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_require_birthday_on_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='employee_can_confirm_appointments',
            field=models.BooleanField(default=False, help_text='Marcado: o funcionário consegue confirmar um agendamento pendente dele mesmo em "Minha Agenda" — só faz sentido com a confirmação automática desligada acima. Desmarcado (padrão): só o admin confirma na Agenda.', verbose_name='funcionário pode confirmar agendamento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='employee_can_create_appointments',
            field=models.BooleanField(default=False, help_text='Marcado: o funcionário consegue criar um encaixe manual pra si mesmo em "Minha Agenda" (só pra ele — não pra outro colega). Desmarcado (padrão): só o admin cria agendamento manual.', verbose_name='funcionário pode agendar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='employee_can_start_appointments',
            field=models.BooleanField(default=False, help_text='Marcado: o funcionário consegue clicar em "Iniciar Atendimento" nos próprios agendamentos em "Minha Agenda", abrindo a comanda no Caixa. Desmarcado (padrão): só o admin inicia atendimento na Agenda.', verbose_name='funcionário pode iniciar atendimento'),
        ),
    ]
