# Generated by Django 5.2.17 on 2026-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_employee_can_confirm_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='weekly_report_email_enabled',
            field=models.BooleanField(default=True, help_text='Toda segunda-feira de manhã, um e-mail com o resumo da semana anterior (faturamento, atendimentos concluídos, novos clientes) é enviado pro(s) responsável(is) do salão. Desmarque pra não receber.', verbose_name='receber relatório semanal por e-mail'),
        ),
    ]
