# Generated by Django 5.2.16 on 2026-07-19 06:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_appointment_unique_active_appointment_per_slot'),
        ('tenants', '0002_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('unit', models.CharField(help_text='ex.: un, ml, g', max_length=10, verbose_name='unidade')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço de custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço de venda')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='estoque atual')),
                ('min_stock_alert', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço unitário')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('reason', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda'), ('service_use', 'Uso em serviço'), ('adjustment', 'Ajuste'), ('loss', 'Perda')], max_length=20, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='scheduling.appointment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_p_tenant__2cb5ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_product_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product', 'created_at'], name='inventory_s_tenant__a22705_idx'),
        ),
    ]
