# Generated by Django 5.2.16 on 2026-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('un', 'Unidade (un)'), ('ml', 'Mililitro (ml)'), ('l', 'Litro (L)'), ('g', 'Grama (g)'), ('kg', 'Quilograma (kg)'), ('cx', 'Caixa (cx)'), ('par', 'Par')], default='un', max_length=10, verbose_name='unidade'),
        ),
    ]
