# Generated by Django 5.2.16 on 2026-07-20 23:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_product_supplier_stockmovement_supplier_and_more'),
        ('tenants', '0004_backfill_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracks_batches',
            field=models.BooleanField(default=False, verbose_name='controla lote/validade'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=60, verbose_name='número do lote')),
                ('expiry_date', models.DateField(verbose_name='validade')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantidade recebida')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantidade restante')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo unitário da compra')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'lote de produto',
                'verbose_name_plural': 'lotes de produto',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantidade consumida')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.productbatch')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_consumptions', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'consumo de lote',
                'verbose_name_plural': 'consumos de lote',
            },
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['tenant', 'product', 'expiry_date'], name='inventory_p_tenant__2d329e_idx'),
        ),
    ]
