# Generated by Django 5.2.16 on 2026-07-21 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_tracks_batches_productbatch_and_more'),
        ('tenants', '0004_backfill_business_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída')], default='in_progress', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'contagem de inventário',
                'verbose_name_plural': 'contagens de inventário',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade esperada')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade contada')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.physicalinventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_items', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'item de contagem',
                'verbose_name_plural': 'itens de contagem',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('count', 'product'), name='unique_product_per_count')],
            },
        ),
    ]
