# Generated by Django 5.2.17 on 2026-08-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_physicalinventorycount_physicalinventorycountitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=True, verbose_name='vender ao cliente'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda'), ('service_use', 'Uso em serviço'), ('recipe_use', 'Insumo de receita (automático)'), ('adjustment', 'Ajuste'), ('loss', 'Perda')], max_length=20, verbose_name='motivo'),
        ),
    ]
