# Generated by Django 5.2.16 on 2026-07-19 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu')], default='pending', max_length=20, verbose_name='status')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço no momento do agendamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='Nulo se criado pelo cliente na página pública.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'date'], name='scheduling__tenant__e16293_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start')],
            },
        ),
    ]
