# Generated by Django 5.2.16 on 2026-07-19 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0002_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('employee', 'date', 'start_time'), name='unique_active_appointment_per_slot'),
        ),
    ]
