# Generated by Django 5.2.16 on 2026-07-19 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('scheduling', '0002_appointment_unique_active_appointment_per_slot'),
        ('services', '0001_initial'),
        ('tenants', '0002_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_per_slot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Atendimento'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'in_progress'])), fields=('employee', 'date', 'start_time'), name='unique_active_appointment_per_slot'),
        ),
    ]
