# Generated by Django 5.2.16 on 2026-08-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_package_client_package'),
        ('scheduling', '0004_appointment_canceled_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='covered_appointments', to='clients.package'),
        ),
    ]
