# Generated by Django 5.2.17 on 2026-08-06 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_debt_balance_clientdebttransaction'),
        ('employees', '0002_workinghours_end_time_2_workinghours_start_time_2_and_more'),
        ('scheduling', '0005_appointment_package'),
        ('services', '0001_initial'),
        ('tenants', '0014_tenant_require_birthday_on_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'date'], name='scheduling__tenant__26cc03_idx'),
        ),
    ]
