# Generated by Django 5.2.16 on 2026-07-19 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('finance', '0002_alter_cashtransaction_category_and_more'),
        ('scheduling', '0003_remove_appointment_unique_active_appointment_per_slot_and_more'),
        ('tenants', '0002_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='saldo de crédito'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='mensalista'),
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.TextField(blank=True, help_text='Alergias, produtos preferidos, observações do atendimento.', verbose_name='preferências'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento da mensalidade'),
        ),
        migrations.CreateModel(
            name='ClientCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='scheduling.appointment')),
                ('related_cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='finance.cashtransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'movimentação de crédito',
                'verbose_name_plural': 'movimentações de crédito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'client', 'created_at'], name='clients_cli_tenant__98174e_idx')],
            },
        ),
    ]
