# Generated by Django 5.2.16 on 2026-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_credit_balance_client_is_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dia de nascimento'),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mês de nascimento'),
        ),
    ]
