# Generated by Django 5.2.16 on 2026-08-04 22:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_birth_day_client_birth_month'),
        ('services', '0001_initial'),
        ('tenants', '0013_tenant_birthday_alert_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor mensal')),
                ('generates_commission', models.BooleanField(default=True, help_text='Marcado: mesmo o cliente não pagando por esse atendimento específico (já incluso na mensalidade), o funcionário ainda recebe a comissão normal, calculada sobre o valor de tabela do serviço. Desmarcado: nenhuma comissão nesses atendimentos.', verbose_name='gera comissão pro funcionário')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='packages', to='services.service', verbose_name='serviços inclusos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_clients', to='clients.package'),
        ),
    ]
