# Generated by Django 5.2.8 on 2026-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_package_client_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_birthday_greeted_on',
            field=models.DateField(blank=True, null=True, verbose_name='último parabéns enviado em'),
        ),
    ]
