# Generated by Django 5.2.17 on 2026-08-06 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_last_birthday_greeted_on'),
        ('finance', '0007_alter_cashtransaction_category'),
        ('scheduling', '0005_appointment_package'),
        ('tenants', '0014_tenant_require_birthday_on_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='saldo devedor'),
        ),
        migrations.CreateModel(
            name='ClientDebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_transactions', to='scheduling.appointment')),
                ('related_cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_transactions', to='finance.cashtransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'movimentação de débito',
                'verbose_name_plural': 'movimentações de débito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'client', 'created_at'], name='clients_cli_tenant__06b58b_idx')],
            },
        ),
    ]
