# Generated by Django 5.2.16 on 2026-07-19 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='nome completo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('default_commission_type', models.CharField(choices=[('percentage', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], default='percentage', max_length=20, verbose_name='tipo de comissão padrão')),
                ('default_commission_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de comissão padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(blank=True, choices=[('percentage', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], max_length=20, null=True, verbose_name='tipo de comissão (override)')),
                ('commission_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor de comissão (override)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='employees.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'vínculo funcionário-serviço',
                'verbose_name_plural': 'vínculos funcionário-serviço',
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fim')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'exceção de agenda',
                'verbose_name_plural': 'exceções de agenda',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='employees_e_tenant__1e34d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeservice',
            constraint=models.UniqueConstraint(fields=('employee', 'service'), name='unique_employee_service'),
        ),
        migrations.AddConstraint(
            model_name='employeeservice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_type__isnull', True), ('commission_value__isnull', True)), models.Q(('commission_type__isnull', False), ('commission_value__isnull', False)), _connector='OR'), name='employeeservice_override_all_or_nothing'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='scheduleexception_full_day_or_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='workinghours_end_after_start'),
        ),
    ]
