# Generated by Django 5.2.17 on 2026-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0013_tenant_birthday_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='end_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='fim do 2º turno'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='start_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='início do 2º turno'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time_2__isnull', True), ('start_time_2__isnull', True)), models.Q(('end_time_2__gt', models.F('start_time_2')), ('end_time_2__isnull', False), ('start_time_2__gte', models.F('end_time')), ('start_time_2__isnull', False)), _connector='OR'), name='workinghours_second_shift_valid'),
        ),
    ]
