# Generated by Django 5.2.16 on 2026-07-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('scheduling', '0004_appointment_canceled_by_client'),
        ('tenants', '0008_tenant_whatsapp_cancel_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('appointment_canceled_by_client', 'Cliente cancelou agendamento')], max_length=40, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='scheduling.appointment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
