# Generated by Django 5.2.16 on 2026-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tenantnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantnotification',
            name='kind',
            field=models.CharField(choices=[('appointment_canceled_by_client', 'Cliente cancelou agendamento'), ('birthday_alert', 'Aniversariante(s) do dia')], max_length=40, verbose_name='tipo'),
        ),
    ]
