# Generated by Django 5.2.17 on 2026-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_tenantnotification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantnotification',
            name='kind',
            field=models.CharField(choices=[('appointment_canceled_by_client', 'Cliente cancelou agendamento'), ('appointment_created_by_client', 'Cliente criou novo agendamento'), ('birthday_alert', 'Aniversariante(s) do dia')], max_length=40, verbose_name='tipo'),
        ),
    ]
